
OBJS += passes/guide/guide_multi.o
OBJS += passes/guide/guide_check.o
OBJS += passes/guide/check/failure_exec.o
OBJS += passes/guide/check/scheduler.o
OBJS += passes/guide/check/matching.o
OBJS += passes/guide/check/region.o
OBJS += passes/guide/check/retime_multiplier.o
OBJS += passes/guide/guide_retime.o
OBJS += passes/guide/guide_design.o
OBJS += passes/guide/guide_design_check.o
OBJS += passes/guide/print_modules.o
