
OBJS += passes/guide/guide_multi.o
OBJS += passes/guide/guide_div.o
OBJS += passes/guide/guide_check.o
OBJS += passes/guide/check/core.o
OBJS += passes/guide/check/fail_exec.o
OBJS += passes/guide/check/scheduler.o
OBJS += passes/guide/check/match.o
OBJS += passes/guide/check/region.o
OBJS += passes/guide/check/retime_multi.o
OBJS += passes/guide/check/div_check.o
OBJS += passes/guide/guide_retime.o
OBJS += passes/guide/guide_design.o
OBJS += passes/guide/guide_design_check.o
OBJS += passes/guide/print_modules.o
